#!/usr/bin/env node
/**
 * Build-time icon fetcher.
 *
 * Reads src/ui/icons.config.json, fetches SVGs from the Iconify API
 * (with local caching for offline use), and generates
 * src/ui/icons-generated.ts with inline SVG constants.
 *
 * Usage:
 *   node scripts/fetch-icons.mjs          # fetch missing, use cache
 *   node scripts/fetch-icons.mjs --force  # re-fetch all icons
 *   node scripts/fetch-icons.mjs --offline # never hit the network
 */
import fs from "node:fs";
import path from "node:path";
import https from "node:https";

const ROOT = path.resolve(import.meta.dirname, "..");
const CONFIG_PATH = path.join(ROOT, "src", "ui", "icons.config.json");
const CACHE_DIR = path.join(ROOT, ".icon-cache");
const OUTPUT_PATH = path.join(ROOT, "src", "ui", "icons-generated.ts");

const args = new Set(process.argv.slice(2));
const FORCE = args.has("--force");
const OFFLINE = args.has("--offline");

function fetchSvg(url) {
  return new Promise((resolve, reject) => {
    https.get(url, { timeout: 15000 }, (res) => {
      if (res.statusCode !== 200) {
        res.resume();
        reject(new Error(`HTTP ${res.statusCode} for ${url}`));
        return;
      }
      let data = "";
      res.on("data", (chunk) => (data += chunk));
      res.on("end", () => resolve(data));
      res.on("error", reject);
    }).on("error", reject);
  });
}

function cacheFile(iconId, color) {
  const colorSuffix = color ? "--" + color.replace(/[^a-zA-Z0-9]/g, "") : "";
  return path.join(CACHE_DIR, iconId.replace(/[:/]/g, "--") + colorSuffix + ".svg");
}

async function getSvg(iconId, color) {
  const cfile = cacheFile(iconId, color);
  if (!FORCE && fs.existsSync(cfile)) {
    return fs.readFileSync(cfile, "utf8");
  }
  if (OFFLINE) {
    throw new Error(`Icon "${iconId}" not in cache and --offline is set. Run without --offline to fetch.`);
  }
  let url = `https://api.iconify.design/${iconId}.svg`;
  if (color) url += `?color=${encodeURIComponent(color)}`;
  process.stderr.write(`  fetching ${iconId}${color ? " (" + color + ")" : ""} ... `);
  const svg = await fetchSvg(url);
  process.stderr.write("ok\n");
  fs.mkdirSync(CACHE_DIR, { recursive: true });
  fs.writeFileSync(cfile, svg);
  return svg;
}

function parseSvg(svg) {
  const viewBoxMatch = svg.match(/viewBox="([^"]+)"/);
  const innerMatch = svg.match(/<svg[^>]*>([\s\S]*)<\/svg>/);
  if (!innerMatch) throw new Error("Could not parse SVG inner content");
  const viewBox = viewBoxMatch ? viewBoxMatch[1] : "0 0 24 24";
  const inner = innerMatch[1].trim();
  return { viewBox, inner };
}

function escapeForTemplateLiteral(str) {
  return str.replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

async function main() {
  const config = JSON.parse(fs.readFileSync(CONFIG_PATH, "utf8"));
  const entries = Object.entries(config);

  // Normalize specs: string "iconId" or object { icon, color }
  const specs = {};
  for (const [name, spec] of entries) {
    if (typeof spec === "string") {
      if (spec.startsWith("=")) continue; // alias
      specs[name] = { icon: spec, color: null };
    } else {
      if (!spec.icon) {
        console.error(`Error: icon "${name}" is missing "icon" property. Got: ${JSON.stringify(spec)}`);
        process.exit(1);
      }
      specs[name] = { icon: spec.icon, color: spec.color || null };
    }
  }

  // Collect all SVGs (dedup by icon+color)
  const svgCache = {};
  for (const [name, { icon, color }] of Object.entries(specs)) {
    const key = icon + (color ? "|" + color : "");
    if (!svgCache[key]) {
      svgCache[key] = await getSvg(icon, color);
    }
  }

  // Build the generated JS code string
  const lines = [];
  lines.push("// Helper function for SVG icons (viewBox auto-detected per icon)");
  lines.push("function _fc(vb, inner, sz) {");
  lines.push("  sz = sz || 20;");
  lines.push("  return '<svg viewBox=\"' + vb + '\" width=\"' + sz + '\" height=\"' + sz + '\" xmlns=\"http://www.w3.org/2000/svg\">' + inner + '</svg>';");
  lines.push("}");

  for (const [name, spec] of entries) {
    if (typeof spec === "string" && spec.startsWith("=")) {
      const alias = spec.slice(1);
      lines.push(`const ${name} = ${alias};`);
    } else {
      const { icon, color } = specs[name];
      const key = icon + (color ? "|" + color : "");
      const svg = svgCache[key];
      const { viewBox, inner } = parseSvg(svg);
      const escaped = escapeForTemplateLiteral(inner);
      lines.push(`const ${name} = _fc("${viewBox}", \`${escaped}\`);`);
    }
  }

  const jsCode = lines.join("\n");

  const output = `// AUTO-GENERATED by scripts/fetch-icons.mjs — do not edit manually.
// To change icons, edit src/ui/icons.config.json and run: npm run build
export const ICONS_JS = ${JSON.stringify(jsCode)};
`;

  fs.writeFileSync(OUTPUT_PATH, output);
  console.log(`Generated ${path.relative(ROOT, OUTPUT_PATH)} (${entries.length} icons)`);
}

main().catch((err) => {
  console.error("Error:", err.message);
  process.exit(1);
});
